# docker-compose.yml
services:
  web:
    build: .
    restart: unless-stopped
    command: python /code/manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/code
    ports:
      - 8008:8008
    depends_on:
      - db
  db:
    image: postgres:12-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
