# Generated by Django 5.0.7 on 2024-08-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['time_create']},
        ),
    ]
